# Generated by Django 3.1.10 on 2021-05-12 00:35

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210512_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='splitter',
        ),
        migrations.RemoveField(
            model_name='splitter',
            name='category',
        ),
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='splitter',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer.splitter'),
        ),
    ]
