# Generated by Django 3.1.10 on 2021-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210512_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sn',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
