# Generated by Django 3.1.10 on 2021-05-16 11:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210514_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='parent',
        ),
        migrations.AlterField(
            model_name='customer',
            name='splitter',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer.customer'),
        ),
    ]
