# Generated by Django 3.1.10 on 2021-05-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20210517_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('splitter32', 'Splitter32'), ('splitter2', 'Splitter2')], max_length=10),
        ),
    ]
