# Generated by Django 3.1.10 on 2021-05-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20210517_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
