# Generated by Django 3.1.10 on 2021-05-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_category_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
