# Generated by Django 3.1.10 on 2021-05-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210512_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='splitter',
            name='parent',
        ),
    ]
