# Generated by Django 3.1.10 on 2021-05-12 01:07

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210512_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='splitter',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer.splitter'),
        ),
    ]
