# Generated by Django 3.1.10 on 2021-05-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210512_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splitter',
            old_name='category',
            new_name='w2',
        ),
    ]
