# Generated by Django 3.1.10 on 2021-05-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_category_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sn',
            field=models.IntegerField(default=0),
        ),
    ]
