# Generated by Django 3.1.10 on 2021-05-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210516_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keywords',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
