# Generated by Django 3.1.10 on 2021-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20210516_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ont',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
